apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-hzyefkxk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-hzyefkxk 
  name: go-hzyefkxk
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-hzyefkxk 
